package com.reg21meme.dross.boss.golem.client;

import com.reg21meme.dross.Dross;
import com.reg21meme.dross.boss.golem.CinderColossus;
import com.reg21meme.dross.boss.golem.GolemDesigns;
import net.minecraft.resources.ResourceLocation;
import software.bernie.geckolib.model.GeoModel;

import java.util.HashMap;
import java.util.Map;

/**
 * Picks each golem's files by its design (see {@link GolemDesigns}): model, animations and its four textures.
 * The files are generated by {@code tools/golems/build.py}.
 */
public class CinderColossusModel extends GeoModel<CinderColossus>
{
    private static final Map<String, Files> FILES = new HashMap<>();

    /** One design's resource locations. */
    public record Files(ResourceLocation model, ResourceLocation animations, ResourceLocation texture,
                        ResourceLocation glow, ResourceLocation flow, ResourceLocation statue)
    {
    }

    public static Files files(CinderColossus golem)
    {
        String id = golem.getDesign().id();
        return FILES.computeIfAbsent(id, key -> new Files(
                new ResourceLocation(Dross.MODID, "geo/entity/cinder_colossus/" + key + ".geo.json"),
                new ResourceLocation(Dross.MODID, "animations/entity/cinder_colossus/" + key + ".animation.json"),
                new ResourceLocation(Dross.MODID, "textures/entity/cinder_colossus/" + key + ".png"),
                new ResourceLocation(Dross.MODID, "textures/entity/cinder_colossus/" + key + "_glow.png"),
                new ResourceLocation(Dross.MODID, "textures/entity/cinder_colossus/" + key + "_flow.png"),
                new ResourceLocation(Dross.MODID, "textures/entity/cinder_colossus/" + key + "_statue.png")));
    }

    @Override
    public ResourceLocation getModelResource(CinderColossus golem)
    {
        return files(golem).model();
    }

    @Override
    public ResourceLocation getTextureResource(CinderColossus golem)
    {
        return files(golem).texture();
    }

    @Override
    public ResourceLocation getAnimationResource(CinderColossus golem)
    {
        return files(golem).animations();
    }
}
