"""Writes ShrineDesigns.java from out/manifest.json (run after build.py)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.normpath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(PROJECT, "src", "main", "java", "com", "reg21meme", "dross", "world", "shrine", "ShrineDesigns.java")

HEADER = '''package com.reg21meme.dross.world.shrine;

import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;

/**
 * The ten designs for a grand ruined portal shrine, numbered 1 to 10. No. 1, the Fallen Cathedral, is the Overworld
 * portal site (the castle, see {@code world.PortalCathedral}). {@code /dross showcase shrines} builds them all in a
 * row to compare.
 * <p>
 * GENERATED by {@code tools/shrines/gen_java.py} from the template generator's manifest: sizes, ground layer and
 * frame position must match the {@code .nbt} files, so change the generator and re-run it rather than editing
 * these numbers by hand.
 */
public final class ShrineDesigns
{
    /** All designs, in number order. */
    public static final List<ShrineDesign> ALL = List.of(
'''

FOOTER = '''
    private ShrineDesigns() {}
}
'''


def main():
    with open(os.path.join(HERE, "out", "manifest.json")) as f:
        entries = sorted(json.load(f), key=lambda e: e["number"])
    lines = []
    for e in entries:
        ox, oy, oz = e["frame_opening_min"]
        axis = "X" if e["frame_axis"] == "x" else "Z"
        ow, oh = e["opening"]
        lines.append(
            f'            new ShrineDesign({e["number"]}, "{e["id"]}", "{e["name"]}", "{e["mood"]}",\n'
            f'                    {e["width"]}, {e["depth"]}, {e["layers"]}, {e["ground_layer"]}, {e["height_above_ground"]}, '
            f'new BlockPos({ox}, {oy}, {oz}), Direction.Axis.{axis}, {ow}, {oh})')
    body = ",\n".join(lines) + ");\n"
    with open(OUT, "w", newline="\n") as f:
        f.write(HEADER + body + FOOTER)
    print("wrote", OUT, len(entries), "designs")


if __name__ == "__main__":
    main()
