package com.reg21meme.dross.world.shrine;

import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;

/**
 * The ten designs for a grand ruined portal shrine, numbered 1 to 10. No. 1, the Fallen Cathedral, is the Overworld
 * portal site (the castle, see {@code world.PortalCathedral}). {@code /dross showcase shrines} builds them all in a
 * row to compare.
 * <p>
 * GENERATED by {@code tools/shrines/gen_java.py} from the template generator's manifest: sizes, ground layer and
 * frame position must match the {@code .nbt} files, so change the generator and re-run it rather than editing
 * these numbers by hand.
 */
public final class ShrineDesigns
{
    /** All designs, in number order. */
    public static final List<ShrineDesign> ALL = List.of(
            new ShrineDesign(1, "fallen_cathedral", "Fallen Cathedral", "gothic, vast",
                    61, 87, 66, 2, 55, new BlockPos(23, 7, 22), Direction.Axis.X, 3, 5),
            new ShrineDesign(2, "shattered_spire", "Shattered Spire", "tall, snapped",
                    75, 73, 64, 2, 61, new BlockPos(24, 11, 34), Direction.Axis.X, 3, 5),
            new ShrineDesign(3, "sunken_temple", "Sunken Temple", "flooded, sinking",
                    63, 73, 34, 2, 31, new BlockPos(30, 11, 28), Direction.Axis.X, 3, 5),
            new ShrineDesign(4, "broken_colosseum", "The Colosseum", "vast, round",
                    75, 65, 32, 2, 29, new BlockPos(36, 6, 32), Direction.Axis.X, 3, 5),
            new ShrineDesign(5, "overgrown_keep", "Overgrown Keep", "fortress, wild",
                    67, 67, 42, 2, 34, new BlockPos(32, 5, 25), Direction.Axis.X, 3, 5),
            new ShrineDesign(6, "fallen_colossus", "Fallen Colossus", "statue, toppled",
                    67, 85, 40, 2, 37, new BlockPos(32, 10, 22), Direction.Axis.X, 3, 5),
            new ShrineDesign(7, "monolith_ring", "Monolith Ring", "ancient, eerie",
                    71, 79, 34, 2, 29, new BlockPos(34, 6, 33), Direction.Axis.X, 3, 5),
            new ShrineDesign(8, "dead_world_tree", "Dead World Tree", "dead, colossal",
                    77, 77, 76, 2, 65, new BlockPos(37, 4, 36), Direction.Axis.X, 3, 5),
            new ShrineDesign(9, "riven_ziggurat", "Riven Ziggurat", "pyramid, split",
                    65, 69, 40, 2, 34, new BlockPos(31, 4, 31), Direction.Axis.X, 3, 5),
            new ShrineDesign(10, "old_observatory", "Old Observatory", "dome, copper",
                    65, 77, 56, 2, 44, new BlockPos(31, 5, 52), Direction.Axis.X, 3, 5));

    private ShrineDesigns() {}
}
