package com.reg21meme.dross.boss.golem;

import java.util.List;

/**
 * The Cinder Colossus design candidates (showcase only; the boss fight isn't built yet).
 * <p>
 * GENERATED by {@code tools/golems/build.py} from the designs in {@code tools/golems/designs/}: don't edit by hand,
 * change the Python design and run the build again. Each design has its own model, animations and four textures:
 * <ul>
 *   <li>{@code geo/entity/cinder_colossus/<id>.geo.json} and {@code animations/entity/cinder_colossus/<id>.animation.json}</li>
 *   <li>{@code textures/entity/cinder_colossus/<id>.png} (the look), {@code <id>_glow.png} (the parts that glow),
 *       {@code <id>_flow.png} (the lava poured over the shell when the volcano erupts; its alpha says how soon each
 *       pixel is reached) and {@code <id>_statue.png} (the golem cooled into obsidian, faded in when it dies)</li>
 * </ul>
 * Bone names: {@code shell_*} the rock shell, {@code molten_*} lava extras of the core form, {@code vent_*} the core
 * form's live eruption, {@code burst_*} the eruption's blast, {@code *_crater} where the craters are (particles).
 * Every other bone is the lava body, always drawn.
 */
public final class GolemDesigns
{
    /**
     * One design.
     *
     * @param number       its place in the showcase row (1 to 1)
     * @param label        its number on the showcase sign (the variations of No. 3 are 3E, 3F...)
     * @param id           file name of its model, animations and textures
     * @param name         its name (fits on a sign)
     * @param mood         one word or two for its style (fits on a sign)
     * @param eruptTicks   length of the eruption animation; afterwards it's erupted
     * @param breakTicks   length of the shell-breaking animation; it holds its last frame afterwards
     * @param burstTicks   when, in that animation, the shell bursts off (the molten extras start to grow then)
     * @param deathTicks   length of the death animation; it holds its last frame afterwards
     * @param walkBlocks   how far the walk animation carries the golem in one loop, for matching its real speed later
     * @param walkTicks    length of one walk loop
     */
    public record Design(int number, String label, String id, String name, String mood, int eruptTicks, int breakTicks,
                         int burstTicks, int deathTicks, float walkBlocks, int walkTicks)
    {
    }

    public static final List<Design> ALL = List.of(
            new Design(1, "3G", "saddleback", "Saddleback", "big twin peaks", 72, 72, 26, 194, 1.875F, 46));

    /** How strongly the lava glows while dormant (it brightens to full as the lava pours over it in the eruption). */
    public static final float DORMANT_GLOW = 0.45F;
    /** Eruption: seconds into it when the volcano blows (the blast's particles)... */
    public static final float ERUPT_BLAST = 1.3F;
    /** ...and when the lava starts pouring over the shell and when it has covered it (the flow texture's reveal). */
    public static final float FLOW_START = 1.4F;
    public static final float FLOW_END = 3.3F;
    /** Death: the lava's glow fades out between these two times (seconds into the death animation)... */
    public static final float GLOW_FADE_START = 4.0F;
    public static final float GLOW_FADE_END = 7.2F;
    /** ...and the obsidian statue texture fades in between these two. */
    public static final float STATUE_FADE_START = 6.0F;
    public static final float STATUE_FADE_END = 9.6F;

    /** The design with this number, or the first one if there's none. */
    public static Design byNumber(int number)
    {
        for (Design design : ALL)
        {
            if (design.number() == number)
            {
                return design;
            }
        }
        return ALL.get(0);
    }

    private GolemDesigns() {}
}
