"""Writes boss/golem/GolemDesigns.java: the design list and the animation timings the mod needs."""
import os

from . import previews

TEMPLATE = '''package com.reg21meme.dross.boss.golem;

import java.util.List;

/**
 * The Cinder Colossus design candidates (showcase only; the boss fight isn't built yet).
 * <p>
 * GENERATED by {{@code tools/golems/build.py}} from the designs in {{@code tools/golems/designs/}}: don't edit by hand,
 * change the Python design and run the build again. Each design has its own model, animations and four textures:
 * <ul>
 *   <li>{{@code geo/entity/cinder_colossus/<id>.geo.json}} and {{@code animations/entity/cinder_colossus/<id>.animation.json}}</li>
 *   <li>{{@code textures/entity/cinder_colossus/<id>.png}} (the look), {{@code <id>_glow.png}} (the parts that glow),
 *       {{@code <id>_flow.png}} (the lava poured over the shell when the volcano erupts; its alpha says how soon each
 *       pixel is reached) and {{@code <id>_statue.png}} (the golem cooled into obsidian, faded in when it dies)</li>
 * </ul>
 * Bone names: {{@code shell_*}} the rock shell, {{@code molten_*}} lava extras of the core form, {{@code vent_*}} the core
 * form's live eruption, {{@code burst_*}} the eruption's blast, {{@code *_crater}} where the craters are (particles).
 * Every other bone is the lava body, always drawn.
 */
public final class GolemDesigns
{{
    /**
     * One design.
     *
     * @param number       its place in the showcase row (1 to {count})
     * @param label        its number on the showcase sign (the variations of No. 3 are 3E, 3F...)
     * @param id           file name of its model, animations and textures
     * @param name         its name (fits on a sign)
     * @param mood         one word or two for its style (fits on a sign)
     * @param eruptTicks   length of the eruption animation; afterwards it's erupted
     * @param breakTicks   length of the shell-breaking animation; it holds its last frame afterwards
     * @param burstTicks   when, in that animation, the shell bursts off (the molten extras start to grow then)
     * @param deathTicks   length of the death animation; it holds its last frame afterwards
     * @param walkBlocks   how far the walk animation carries the golem in one loop, for matching its real speed later
     * @param walkTicks    length of one walk loop
     */
    public record Design(int number, String label, String id, String name, String mood, int eruptTicks, int breakTicks,
                         int burstTicks, int deathTicks, float walkBlocks, int walkTicks)
    {{
    }}

    public static final List<Design> ALL = List.of(
{entries});

    /** How strongly the lava glows while dormant (it brightens to full as the lava pours over it in the eruption). */
    public static final float DORMANT_GLOW = {dormant}F;
    /** Eruption: seconds into it when the volcano blows (the blast's particles)... */
    public static final float ERUPT_BLAST = {blast}F;
    /** ...and when the lava starts pouring over the shell and when it has covered it (the flow texture's reveal). */
    public static final float FLOW_START = {flow0}F;
    public static final float FLOW_END = {flow1}F;
    /** Death: the lava's glow fades out between these two times (seconds into the death animation)... */
    public static final float GLOW_FADE_START = {glow0}F;
    public static final float GLOW_FADE_END = {glow1}F;
    /** ...and the obsidian statue texture fades in between these two. */
    public static final float STATUE_FADE_START = {stat0}F;
    public static final float STATUE_FADE_END = {stat1}F;

    /** The design with this number, or the first one if there's none. */
    public static Design byNumber(int number)
    {{
        for (Design design : ALL)
        {{
            if (design.number() == number)
            {{
                return design;
            }}
        }}
        return ALL.get(0);
    }}

    private GolemDesigns() {{}}
}}
'''


def _ticks(seconds):
    return int(round(seconds * 20.0))


def write_design_list(path, built):
    lines = []
    blast = None
    for d, m, animations, textures in built:
        brk = animations["break_shell"]
        dth = animations["death"]
        wlk = animations["walk"]
        eru = animations.get("erupt")
        erupt_ticks = _ticks(eru.length) if eru else 0
        if eru:
            blast = eru.meta["blast"]
        lines.append(f'            new Design({d.NUMBER}, "{d.LABEL}", "{d.ID}", "{d.NAME}", "{d.MOOD}", {erupt_ticks}, '
                     f'{_ticks(brk.length)}, {_ticks(brk.meta["burst"])}, {_ticks(dth.length)}, '
                     f'{wlk.meta["stride_blocks"]:.3f}F, {_ticks(wlk.length)})')
    text = TEMPLATE.format(entries=",\n".join(lines), count=len(built), blast=blast if blast is not None else 0.9,
                           flow0=previews.FLOW_REVEAL[0], flow1=previews.FLOW_REVEAL[1], dormant=previews.DORMANT_GLOW,
                           glow0=previews.GLOW_FADE[0], glow1=previews.GLOW_FADE[1],
                           stat0=previews.STATUE_FADE[0], stat1=previews.STATUE_FADE[1])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
